baseURL: //payfunc.com/
languageCode: en-us
DefaultContentLanguage: "en"
title: PayFunc
tagline: "Easy to integrate Payment API for the Nordics."
theme: hugo-theme-html5
MetaDataFormat: yaml
params:
  onlyLogotype: true
  logotype: "logo/payfunc-d1.svg"
  footer: "© PayFunc"
  CSS:
    - "css/header.css"
    - "css/footer.css"
    - "css/color.css"
    - "css/content.css"
    - "css/layout.css"
    - "css/list.css"
    - "css/menu.css"
    - "css/text.css"
    - "css/code.css"
    - "css/narrow.css"
    - "css/form.css"
    - "css/home.css"
  ListMode: "summary"
  FrontPageMode: "full"
  FrontPageSection: "home"
  NavigationInHeader: true
  Prefix:
    - "og: http://opy.me/ns#"
googleAnalytics: "UA-151967911-1"
PluralizeListTitles: false
pygmentsCodeFences: true
pygmentsUseClasses: true
blackfriday:
  extensions:
    - hardLineBreak
