baseURL: https://payfunc.com/
languageCode: en
defaultContentLanguage: "en"
title: PayFunc
theme: hugo-theme-html5
MetaDataFormat: yaml
params:
  onlyLogotype: true
  logotype: "logo/payfunc-d1.svg"
  tagline: "Payments for Programmers"
  description: "PayFunc provides easy to integrate solutions for payments and monetary transactions for your web and app based needs."
  keywords: "Payment, PSP, Card Payment, Transaction, Payment API, PCI DSS Level 1, Visa, MasterCard"
  author: "PayFunc"
  footer: "© PayFunc"
  CSS:
    - "css/header.css"
    - "css/footer.css"
    - "css/color.css"
    - "css/content.css"
    - "css/layout.css"
    - "css/list.css"
    - "css/menu.css"
    - "css/text.css"
    - "css/code.css"
    - "css/narrow.css"
    - "css/form.css"
    - "css/home.css"
  ListMode: "summary"
  FrontPageMode: "full"
  FrontPageSection: "home"
  NavigationInHeader: true
  Prefix:
    - "og: http://opy.me/ns#"
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
enableGitInfo: true
enableRobotsTXT: true
googleAnalytics: "UA-151967911-1"
PluralizeListTitles: false
pygmentsCodeFences: true
pygmentsUseClasses: true
blackfriday:
  extensions:
    - hardLineBreak
