baseURL: https://cardfunc.com/
languageCode: en
defaultContentLanguage: "en"
title: CardFunc
theme: hugo-theme-html5
MetaDataFormat: yaml
params:
  onlyLogotype: true
  logotype: "logo/cardfunc-d1.svg"
  tagline: "Card Processing for PSP:s"
  description: "CardFunc provides easy to integrate solutions for card payments for payment system providers."
  keywords: "Payment, PSP, Card Payment, Transaction, Payment API, PCI DSS Level 1, Visa, MasterCard"
  author: "CardFunc"
  footer: "© CardFunc"
  CSS:
    - "css/header.css"
    - "css/footer.css"
    - "css/color.css"
    - "css/layout.css"
    - "css/text.css"
    - "css/code.css"
    - "css/narrow.css"
    - "css/form.css"
    - "css/home.css"
  ListMode: "summary"
  FrontPageMode: "full"
  FrontPageSection: "home"
  NavigationInHeader: true
  Prefix:
    - "og: http://opy.me/ns#"
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
enableGitInfo: true
enableRobotsTXT: true
googleAnalytics: "UA-151967911-1"
PluralizeListTitles: false
pygmentsCodeFences: true
pygmentsUseClasses: true
blackfriday:
  extensions:
    - hardLineBreak
markup:
  goldmark:
    renderer:
      unsafe: true